"""Add death_date, photo_file_id, gender

Revision ID: 637e2fe1e15b
Revises: 445a32bf00f2
Create Date: 2025-12-04 05:49:14.202317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637e2fe1e15b'
down_revision: Union[str, Sequence[str], None] = '445a32bf00f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
